sudo: false

addons:
 apt:
   packages:

language:

before_cache:

cache:
  directories:

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:

before_deploy:

deploy:
